=== MattMurnaghan/RealView/assets/json/kline_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "e": {
        "type": "string"
      },
      "E": {
        "type": "integer"
      },
      "s": {
        "type": "string"
      },
      "k": {
        "type": "object",
        "properties": {
          "t": {
            "type": "integer"
          },
          "T": {
            "type": "integer"
          },
          "s": {
            "type": "string"
          },
          "i": {
            "type": "string"
          },
          "f": {
            "type": "integer"
          },
          "L": {
            "type": "integer"
          },
          "o": {
            "type": "string"
          },
          "c": {
            "type": "string"
          },
          "h": {
            "type": "string"
          },
          "l": {
            "type": "string"
          },
          "v": {
            "type": "string"
          },
          "n": {
            "type": "integer"
          },
          "x": {
            "type": "boolean"
          },
          "q": {
            "type": "string"
          },
          "V": {
            "type": "string"
          },
          "Q": {
            "type": "string"
          },
          "B": {
            "type": "string"
          }
        },
        "required": [
          "t",
          "T",
          "i",
          "o",
          "c",
          "h",
          "l",
          "v",
          "n",
          "x"
        ]
      }
    },
    "required": [
      "e",
      "E",
      "s",
      "k"
    ]
  }

=== MattMurnaghan/RealView/assets/json/btcusdt-kline.json
{
    "e": "kline",
    "E": 1657675754011,
    "s": "BTCUSDT",
    "k": {
        "t": 1657675500000,
        "T": 1657675799999,
        "s": "BTCUSDT",
        "i": "5m",
        "f": 1458722581,
        "L": 1458731181,
        "o": "19411.85000000",
        "c": "19405.05000000",
        "h": "19415.00000000",
        "l": "19378.37000000",
        "v": "297.07434000",
        "n": 8601,
        "x": false,
        "q": "5762128.25577910",
        "V": "138.36981000",
        "Q": "2683904.79370620",
        "B": "0"
    }
}
